version: "3"
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fipe
    ports:
      - 5432:5432
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dummy_dump.sql
  server:
    image: node:20
    volumes:
      - ./server:/app
    working_dir: /app
    command: bash -c "npm install && npm run dev"
    ports:
      - 3333:3333
    depends_on:
      - db
  client:
    image: node:20
    volumes:
      - ./client:/app
    working_dir: /app
    command: bash -c "npm install && npm run dev"
    ports:
      - 5173:5173
    depends_on:
      - server
